### ISSUE TITLE
Android 1-on-1 VideoCall - Unable to join channel using DynamicKey generated with RtcTokenBuilderSample.

### ISSUE THREAD

**Issue by michaelihuoma01** [AgoraIO/Basic-Video-Call#127] opened 2020-01-12 05:56 UTC

**Comment by michaelihuoma01** [comment] 2020-01-12 06:01
After successfully implementing Agora 1-on-1 VideoCall for android using android studio, users can successfully join th channel and make video calls using the Temp Token generated on my dashboard which expires after 24hrs, I tried taking the application to Live mode and generated a dynamic key using RtcTokenBuilderSample on eclipse IDE as described in the docs, users are unable to join the channel using the dynamic key; the screen hangs once a user picks the call

**Comment by plutoless** [comment] 2020-01-12 13:27
could you pls help share a token you generated and corresponding uid/channel for me to check? for safety you can set the token to expire in 5 mins. Note the channel/uid you are trying to join needs to match with the parameters given to generate the token you want.

**Comment by michaelihuoma01** [comment] 2020-01-15 08:03
This is the token generated below 0066dfd1d1807744b1ca10805e7c471f13eIACOPnGFQAReF4FpZND4uwB+B1u9ujxlGXC0D01aKHlMvGGQNbEcAAAAAIgAvUmOaxmvpXQQAAQBVKOhdAgBVKOhdAwBVKOhdBABVKOhd
channel - olangodemo

**Comment by plutoless** [comment] 2020-01-15 09:28
i tried to decode your token but it seems to be invalid. which docs are you referring to when setup?

**Comment by michaelihuoma01** [comment] 2020-01-15 16:01
https://docs.agora.io/en/Voice/token_server_java?platform=Java
This is the docs I used to generate my dynamic key

**Comment by michaelihuoma01** [comment] 2020-01-18 15:48
Hello @plutoless please help!

**Comment by plutoless** [comment] 2020-01-19 03:24
@michaelihuoma01  i did a quick test and it turned out to be working properly. could you pls describe how you generate the token?

**Comment by plutoless** [comment] 2020-01-19 03:25
or if you can provide your minimum reproducible project i can also help take a look

**Comment by michaelihuoma01** [comment] 2020-01-19 16:59
I followed exactly the steps in the docs

**Comment by michaelihuoma01** [comment] 2020-01-19 17:01
This is my logcat for incoming call using the token 

`are this message

Share with

agoraiodev










Add a message, if you’d like.
Magikmike
2020-01-12 06:41:45.875 2113-2501/system_process I/ActivityManager: START u0 {cmp=com.olango.vista/.CallActivity (has extras)} from uid 10058 on display 0
2020-01-12 06:41:45.877 2113-2501/system_process D/ActivityManager: TopActivityInfo, pkgName: com.olango.vista activityName: com.olango.vista.CallActivity callingPackage: com.olango.vista  bstSpecialAppKeyboardHandlingEnabled = false
2020-01-12 06:41:45.886 2113-2280/system_process D/ActivityManager: TopActivityInfo, pkgName: com.olango.vista activityName: com.olango.vista/.CallActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
2020-01-12 06:41:45.918 5361-5361/com.olango.vista I/CallActivity: checkSelfPermission android.permission.RECORD_AUDIO 22
2020-01-12 06:41:45.920 5361-5361/com.olango.vista I/CallActivity: checkSelfPermission android.permission.CAMERA 23
2020-01-12 06:41:45.921 5361-5361/com.olango.vista I/CallActivity: checkSelfPermission android.permission.WRITE_EXTERNAL_STORAGE 24
2020-01-12 06:41:45.921 5361-5361/com.olango.vista I/CallActivity: initializeAgoraEngine mRtcEngine :io.agora.rtc.internal.RtcEngineImpl@e5424b0
2020-01-12 06:41:45.946 5361-5361/com.olango.vista I/CallActivity: setupLocalVideo startPreview enter << ret :0
2020-01-12 06:41:46.052 5361-6090/com.olango.vista D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=ChatActivityy, ga_previous_id(_pi)=-4613530527131053219, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053214}]
2020-01-12 06:41:47.228 2113-2134/system_process I/ActivityManager: Displayed com.olango.vista/.CallActivity: +1s341ms
2020-01-12 06:41:47.230 2113-2501/system_process D/InputMethodManagerService: packageName=com.olango.vista, activityName=.CallActivity
2020-01-12 06:41:47.788 2637-6111/com.google.android.gms V/FA-SVC: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=ChatActivityy, ga_previous_id(_pi)=-4613530527131053219, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053214}]
2020-01-12 06:41:47.800 2637-6111/com.google.android.gms V/FA-SVC: Event recorded: Event{appId='com.olango.vista', name='screen_view(_vs)', params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=ChatActivityy, ga_previous_id(_pi)=-4613530527131053219, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053214}]}
2020-01-12 06:41:59.527 5361-5361/com.olango.vista I/CallActivity: setupLocalVideo startPreview enter << ret :0
2020-01-12 06:41:59.538 5361-5361/com.olango.vista I/CallActivity: joinChannel enter ret :0
2020-01-12 06:42:19.070 5361-5412/com.olango.vista I/CallActivity: onInviteEndByMyself channelID = olangodemo  account = 
2020-01-12 06:42:19.138 5361-6090/com.olango.vista D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=CallActivity, ga_previous_id(_pi)=-4613530527131053214, ga_screen_class(_sc)=ChatActivityy, ga_screen_id(_si)=-4613530527131053219}]
2020-01-12 06:42:19.219 5361-6090/com.olango.vista D/FA: Logging event (FE): user_engagement(_e), Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=33117, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053214}]
2020-01-12 06:42:19.562 2113-2134/system_process V/WindowManager: isVisibleLw false for win : Window{f242ee0 u0 com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:42:19.562 2113-2134/system_process V/WindowManager: isVisibleLw false for win : Window{b4e9ff6 u0 SurfaceView - com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:42:19.562 2113-2134/system_process V/WindowManager: isVisibleLw false for win : Window{37b3ff7 u0 SurfaceView - com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:42:19.588 2113-2281/system_process V/WindowManager: isVisibleLw false for win : Window{f242ee0 u0 com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:42:19.588 2113-2281/system_process V/WindowManager: isVisibleLw false for win : Window{37b3ff7 u0 SurfaceView - com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:42:19.600 2637-6155/com.google.android.gms V/FA-SVC: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=CallActivity, ga_previous_id(_pi)=-4613530527131053214, ga_screen_class(_sc)=ChatActivityy, ga_screen_id(_si)=-4613530527131053219}]
2020-01-12 06:42:19.602 2113-2125/system_process V/WindowManager: isVisibleLw false for win : Window{f242ee0 u0 com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:42:19.636 2637-6155/com.google.android.gms V/FA-SVC: Event recorded: Event{appId='com.olango.vista', name='screen_view(_vs)', params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=CallActivity, ga_previous_id(_pi)=-4613530527131053214, ga_screen_class(_sc)=ChatActivityy, ga_screen_id(_si)=-4613530527131053219}]}
2020-01-12 06:42:19.669 2637-6155/com.google.android.gms V/FA-SVC: Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=33117, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053214}]
2020-01-12 06:42:19.680 2637-6155/com.google.android.gms V/FA-SVC: Event recorded: Event{appId='com.olango.vista', name='user_engagement(_e)', params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=33117, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053214}]}
2020-01-12 06:42:19.829 5361-5361/com.olango.vista I/CallActivity: onDestroy`

**Comment by michaelihuoma01** [comment] 2020-01-19 17:07
Logcat of outgoing calls


are this message

Share with

agoraiodev










Add a message, if you’d like.
Magikmike
2020-01-12 06:47:11.476 2113-2280/system_process I/ActivityManager: START u0 {cmp=com.olango.vista/.CallActivity (has extras)} from uid 10058 on display 0
2020-01-12 06:47:11.477 2113-2280/system_process D/ActivityManager: TopActivityInfo, pkgName: com.olango.vista activityName: com.olango.vista.CallActivity callingPackage: com.olango.vista  bstSpecialAppKeyboardHandlingEnabled = false
2020-01-12 06:47:11.486 2113-2283/system_process D/ActivityManager: TopActivityInfo, pkgName: com.olango.vista activityName: com.olango.vista/.CallActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
2020-01-12 06:47:11.537 5361-5361/com.olango.vista I/CallActivity: checkSelfPermission android.permission.RECORD_AUDIO 22
2020-01-12 06:47:11.539 5361-5361/com.olango.vista I/CallActivity: checkSelfPermission android.permission.CAMERA 23
2020-01-12 06:47:11.540 5361-5361/com.olango.vista I/CallActivity: checkSelfPermission android.permission.WRITE_EXTERNAL_STORAGE 24
2020-01-12 06:47:11.542 5361-5361/com.olango.vista I/CallActivity: initializeAgoraEngine mRtcEngine :io.agora.rtc.internal.RtcEngineImpl@e5424b0
2020-01-12 06:47:11.574 5361-5361/com.olango.vista I/CallActivity: setupLocalVideo startPreview enter << ret :0
2020-01-12 06:47:11.598 5361-5361/com.olango.vista I/CallActivity: joinChannel enter ret :0
2020-01-12 06:47:11.711 5361-6318/com.olango.vista D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=ChatActivityy, ga_previous_id(_pi)=-4613530527131053219, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053209}]
2020-01-12 06:47:12.309 2113-2124/system_process D/InputMethodManagerService: packageName=com.olango.vista, activityName=.CallActivity
2020-01-12 06:47:12.357 2113-2134/system_process I/ActivityManager: Displayed com.olango.vista/.CallActivity: +870ms
2020-01-12 06:47:12.441 2637-6339/com.google.android.gms V/FA-SVC: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=ChatActivityy, ga_previous_id(_pi)=-4613530527131053219, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053209}]
2020-01-12 06:47:12.452 2637-6339/com.google.android.gms V/FA-SVC: Event recorded: Event{appId='com.olango.vista', name='screen_view(_vs)', params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=ChatActivityy, ga_previous_id(_pi)=-4613530527131053219, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053209}]}
2020-01-12 06:47:41.987 5361-5412/com.olango.vista I/CallActivity: onInviteEndByPeer channelID = olangodemo account = +2347059465854
2020-01-12 06:47:42.073 5361-6318/com.olango.vista D/FA: Logging event (FE): user_engagement(_e), Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=30378, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053209}]
2020-01-12 06:47:42.109 5361-6318/com.olango.vista D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=CallActivity, ga_previous_id(_pi)=-4613530527131053209, ga_screen_class(_sc)=ChatActivityy, ga_screen_id(_si)=-4613530527131053219}]
2020-01-12 06:47:42.293 2113-2134/system_process V/WindowManager: isVisibleLw false for win : Window{ea44393 u0 com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:47:42.293 2113-2134/system_process V/WindowManager: isVisibleLw false for win : Window{fa30773 u0 SurfaceView - com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:47:42.317 2113-3640/system_process V/WindowManager: isVisibleLw false for win : Window{ea44393 u0 com.olango.vista/com.olango.vista.CallActivity}
2020-01-12 06:47:42.341 2637-6339/com.google.android.gms V/FA-SVC: Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=30378, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053209}]
2020-01-12 06:47:42.372 2637-6339/com.google.android.gms V/FA-SVC: Event recorded: Event{appId='com.olango.vista', name='user_engagement(_e)', params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=30378, ga_screen_class(_sc)=CallActivity, ga_screen_id(_si)=-4613530527131053209}]}
2020-01-12 06:47:42.417 2637-6339/com.google.android.gms V/FA-SVC: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=CallActivity, ga_previous_id(_pi)=-4613530527131053209, ga_screen_class(_sc)=ChatActivityy, ga_screen_id(_si)=-4613530527131053219}]
2020-01-12 06:47:42.429 2637-6339/com.google.android.gms V/FA-SVC: Event recorded: Event{appId='com.olango.vista', name='screen_view(_vs)', params=Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=CallActivity, ga_previous_id(_pi)=-4613530527131053209, ga_screen_class(_sc)=ChatActivityy, ga_screen_id(_si)=-4613530527131053219}]}
2020-01-12 06:47:42.545 5361-5361/com.olango.vista I/CallActivity: onDestroy

**Comment by michaelihuoma01** [comment] 2020-01-19 17:09
Do you need a link to my demo APK?

**Comment by plutoless** [comment] 2020-01-19 17:16
hi @michaelihuoma01 i think your apk project should be fine, as long as it works with your temp token generated from dashboard. as i mentioned above, the token i got from you cannot be decoded successfully with our internal tools - while the one i generated myself can, so i guess it's somehow invalid. What i would like to know is which values you changed in order to generate token. if you can provide me your token generator file, and hide you app certificate, that would also be helpful.

**Comment by michaelihuoma01** [comment] 2020-01-20 00:12
[RtcTokenBuilderSample.zip](https://github.com/AgoraIO/Basic-Video-Call/files/4083960/RtcTokenBuilderSample.zip)
This is my token generator file.

**Comment by plutoless** [comment] 2020-01-20 02:55
try using buildTokenWithUid instead of buildTokenWithUserAccount, you didn't specify a valid account value when you call with buildTokenWithUserAccount, plus buildTokenWithUserAccount is used to work with string account. usually you just need to use int uid and should stick to buildTokenWithUid function.

**Comment by michaelihuoma01** [comment] 2020-01-23 06:59
Hello @plutoless  i tried building with buildTokenwithUid it still doesn't work, it does nothing after the call is picked.
This is the token generated
0066dfd1d1807744b1ca10805e7c471f13eIADDJJKKYZ0/RwJezIAmZdIDFJ919V2NTCP9ppYH43XQWmQNbEcAAAAAIgDARnKIxH0nXgQAAQDDXyiZAgDDXyiZAwDDXyiZBADDXyiZ
channel name: olangodemo

**Comment by michaelihuoma01** [comment] 2020-01-23 07:06
Any idea on how i can get an account name or an uid? Because i left the uid field null

**Comment by michaelihuoma01** [comment] 2020-01-24 00:02
hello @plutoless

**Comment by plutoless** [comment] 2020-01-27 14:53
@michaelihuoma01 the token you provided above can now be properly decoded. 
1. it seems you provide some values for uid when calculating the token, you need to make sure the uid matches with the one you use when join channel. or you can provide uid 0 when calculating the token.
2. it seems you provide a very large timestamp for token privilege, you can provide 0 if you don't want it to expire within 24hours.

**Comment by plutoless** [comment] 2020-01-27 14:54
try to match the uid, or use uid 0 when calculating the token and check if it works for you.

**Comment by michaelihuoma01** [comment] 2020-01-28 15:53
It still doesn't work

**Comment by michaelihuoma01** [comment] 2020-01-28 15:58
[callActivity.zip](https://github.com/AgoraIO/Basic-Video-Call/files/4123264/callActivity.zip)
Can you please take a look at my callActivity class and see what i may be doing wrong?

**Comment by michaelihuoma01** [comment] 2020-01-28 15:58
I set my uid and timestamp to 0 and generated a new key
But i'm still having the same issue

**Comment by michaelihuoma01** [comment] 2020-01-28 16:03
0066dfd1d1807744b1ca10805e7c471f13eIACSXMUNkYBNzrAInXbr++gas7Ez59siFePRcpL40IMciGQNbEcAAAAAIgBdIc1+Q5AxXgQAAQDBPjBeAgDBPjBeAwDBPjBeBADBPjBe

This is the new token generated

**Comment by michaelihuoma01** [comment] 2020-01-29 13:44
hello @plutoless

**Comment by plutoless** [comment] 2020-01-30 12:31
do you still have issues joining channel? from backend i can see you successfully joined channel yesterday. the devices joined are 1 nokia and 1 samsung.

**Comment by michaelihuoma01** [comment] 2020-02-01 02:20
I joined the channel using a generated temp token
The dynamic key generated using the buildtokenwithuid method stated above didn't work

**Comment by michaelihuoma01** [comment] 2020-02-01 02:21
It works perfectly well using a generated temp token
I'm only having issues generating a dynamic key

**Comment by plutoless** [comment] 2020-02-01 08:19
the temp token ignores uid check, while buildTokenWithUid checks uid if you give when generating. Could you pls share your latest token generator project for me to take a look?

**Comment by plutoless** [comment] 2020-02-01 08:19
sorry my reply could delay a little bit since we are having spring festival in the moment

**Comment by michaelihuoma01** [comment] 2020-02-01 10:39
[RtcTokenBuilderSample.zip](https://github.com/AgoraIO/Basic-Video-Call/files/4142435/RtcTokenBuilderSample.zip)

**Comment by michaelihuoma01** [comment] 2020-02-01 10:41
Thats my latest token generator file
Also please help me check my callactivity class above, maybe i'm doing something wrong
Thanks.

**Comment by michaelihuoma01** [comment] 2020-02-01 10:42
No problem, make sure you do enjoy the festival

**Comment by plutoless** [comment] 2020-02-03 09:23
@michaelihuoma01  i did a quick test. you need to change expirationTimeInSeconds to some larger value, i used 3600 in this case. you set it to 0 which means it will expire right away. Previously i mentioned you can set expirationTimestamp to 0 it means to set timestamp at line 24 to 0. You are setting the value at line 12 to 0 which is an offset. i changed that value to 3600 (expires in 1 hour) and i can use the token to join channel successfully.

**Comment by michaelihuoma01** [comment] 2020-02-04 07:07
Oh wow! Thank you so much, it worked 😭😭😭
So how do I get to set the timestamp not to expire or for a long time like 3 months or even 6 months

**Comment by plutoless** [comment] 2020-02-05 17:27
@michaelihuoma01 just kind note. the token will expire in 24 hours anyway so it makes no sense to generate a token which expires in 6months. you should ask your server to generate a new token for you every time you join the channel, instead of generating a static token and use it always.

**Comment by plutoless** [comment] 2020-02-05 17:27
after all, glad it works. closing.

**Closed by plutoless** 2020-02-05 17:27 UTC

**Comment by michaelihuoma01** [comment] 2020-02-05 17:41
@plutoless please any idea how i can ask my server to generate a new token everytime i join a channel?

**Comment by plutoless** [comment] 2020-02-07 07:01
just send .a request?
