### ISSUE TITLE
how to recorder broadcasting video from iOS and android?. any agora SDK available for On-premise Recording?

### ISSUE THREAD

**Issue by Lalitchaudhary2** [AgoraIO/Basic-Video-Call#120] opened 2019-12-11 05:32 UTC

**Comment by plutoless** [comment] 2019-12-11 06:40
yes we do
https://docs.agora.io/en/Recording/product_recording?platform=Linux

**Comment by Lalitchaudhary2** [comment] 2019-12-11 11:12
thanks for your reply. i read the above link, also i am able to push video in our server wia command line but not able to push wia API from android and iOS. we add the AgoraRTCEngine  for video broadcasting, we need to add other SDK for Record video from Android ?

**Comment by digitallysavvy** [comment] 2019-12-12 02:46
@Lalitchaudhary2 you should check out the [On-Premise Recording with Nodejs](https://github.com/AgoraIO/Basic-Recording/tree/master/On-Premise-Recording-Nodejs). It uses Express service to trigger the On-Prem CPP

**Comment by manojaddon** [comment] 2019-12-16 12:39
Hy .. Thank you for your response.
 by using your response code or link  we have sucessfully push record on server but we have one problem in this task.

the Problem is that when we want to record the Live stream the yes , i has been recorded but it is creating two different file for Audio and video , so audio has been played separate and also video pleayed separate  , so we need to push only one file (MP4) but we don't know how to combine it in your given program.

so can you please Help us to resolve this perticular issue ?

**Comment by digitallysavvy** [comment] 2019-12-19 22:55
@manojaddon since the issue you have raised is completed we should close this ticket. 

Regarding the new question you have posted, please email me directly: hermes@agora.io or[ join our community slack](https://join.slack.com/t/agoraiodev/shared_invite/enQtNjk0OTg4ODgyNTc5LTczOWQ0YjBkMTMwZDFmYzViYjIxNjg4YTM0OWEzZjdkODM1NDNmOTM1ZTE4Y2Q1ZWUwMjNjMzMxMmZiNGI3ODg) and we can discuss the solution there in real-time.

**Closed** 2019-12-19 22:55 UTC

**Comment by milan656** [comment] 2021-07-13 13:25
hi, how to save our video,audio recording in combine using android in agora? we need to which configuration add in android side ?
please tel me step by step.

**Comment by Sanskar619** [comment] 2023-02-15 10:03
how can we record a video in Agora SDK while using another server not linux or ubuntu
How can I acheive this?
